#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Sage AI — Interactive Setup Script
====================================
Run this script first after downloading Sage AI.
It creates your personal .env file step by step.

Usage:
    python setup.py

Estimated time: 10–20 minutes
Requirements: Python 3.9+
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path

# ── Colour output ─────────────────────────────────────────────────────────────
GREEN  = "\033[92m"
YELLOW = "\033[93m"
CYAN   = "\033[96m"
RED    = "\033[91m"
BOLD   = "\033[1m"
RESET  = "\033[0m"

def p(text, color=RESET):   print(f"{color}{text}{RESET}")
def h(text):                print(f"\n{BOLD}{CYAN}{'='*60}\n  {text}\n{'='*60}{RESET}")
def ok(text):               print(f"{GREEN}✅ {text}{RESET}")
def warn(text):             print(f"{YELLOW}⚠️  {text}{RESET}")
def tip(text):              print(f"{CYAN}💡 {text}{RESET}")

def ask(prompt, default="", secret=False):
    """Prompt for input. Press Enter to use the default."""
    import getpass
    display = f"{CYAN}{prompt}{RESET}"
    if default:
        display += f" [{YELLOW}{default}{RESET}]"
    display += ": "
    if secret:
        val = getpass.getpass(display)
    else:
        val = input(display)
    return val.strip() or default

def ask_yn(prompt, default=True):
    suffix = " [Y/n]: " if default else " [y/N]: "
    val = input(f"{CYAN}{prompt}{RESET}{suffix}").strip().lower()
    if not val:
        return default
    return val in ("y", "yes")

def check_python_version():
    if sys.version_info < (3, 9):
        p(f"❌  Python 3.9+ is required. You are running Python {sys.version}", RED)
        p("    Download from: https://www.python.org/downloads/", RED)
        sys.exit(1)

# ── Banner ────────────────────────────────────────────────────────────────────
def banner():
    print(f"""
{BOLD}{CYAN}
  ███████╗ █████╗  ██████╗ ███████╗
  ██╔════╝██╔══██╗██╔════╝ ██╔════╝
  ███████╗███████║██║  ███╗█████╗
  ╚════██║██╔══██║██║   ██║██╔══╝
  ███████║██║  ██║╚██████╔╝███████╗
  ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
       AI Solopreneur Automation
{RESET}
  Welcome to the Sage AI Setup Wizard!
  This script will create your personal .env configuration file.

  Press Enter to skip any optional field — you can add it later.
""")


# ── .env template ─────────────────────────────────────────────────────────────
ENV_TEMPLATE = """# ================================================================
# Sage AI — Your personal configuration file
# DO NOT commit or share this file. It contains secret API keys.
# Generated by setup.py
# ================================================================

# ── Flask server ──────────────────────────────────────────────
FLASK_APP=backend/flask_server.py
FLASK_PORT={FLASK_PORT}
FLASK_DEBUG=0
PYTHONPATH=.

# ── Your site URL (used for redirects) ────────────────────────
# Set this to your Cloudflare Pages URL after deploying
SITE_URL={SITE_URL}

# ── AI API keys (required) ─────────────────────────────────────
# Groq — free, fast: https://console.groq.com/ → API Keys
GROQ_API_KEY={GROQ_API_KEY}

# Perplexity — optional research feature: https://www.perplexity.ai/settings/api
PERPLEXITY_API_KEY={PERPLEXITY_API_KEY}

# ── Notion ────────────────────────────────────────────────────
# Integration token: https://www.notion.so/my-integrations
NOTION_API_KEY={NOTION_API_KEY}
# 32-character ID from your Content Pool database URL
NOTION_CONTENT_POOL_DB_ID={NOTION_CONTENT_POOL_DB_ID}
NOTION_EVIDENCE_LEDGER_DB_ID={NOTION_EVIDENCE_LEDGER_DB_ID}
SAGE_ENABLE_NOTION={SAGE_ENABLE_NOTION}

# ── Bluesky (SNS auto-posting) ────────────────────────────────
# Settings → App Passwords → Add App Password (NOT your login password)
BLUESKY_HANDLE={BLUESKY_HANDLE}
BLUESKY_APP_PASSWORD={BLUESKY_APP_PASSWORD}
SAGE_ENABLE_BLUESKY={SAGE_ENABLE_BLUESKY}

# ── Twitter/X (optional) ──────────────────────────────────────
# https://developer.twitter.com/ → Project → Keys and Tokens
TWITTER_API_KEY={TWITTER_API_KEY}
TWITTER_API_SECRET={TWITTER_API_SECRET}
TWITTER_ACCESS_TOKEN={TWITTER_ACCESS_TOKEN}
TWITTER_ACCESS_TOKEN_SECRET={TWITTER_ACCESS_TOKEN_SECRET}
TWITTER_BEARER_TOKEN={TWITTER_BEARER_TOKEN}

# ── Instagram (optional — requires Business account) ──────────
INSTAGRAM_ACCESS_TOKEN={INSTAGRAM_ACCESS_TOKEN}
INSTAGRAM_ACCOUNT_ID={INSTAGRAM_ACCOUNT_ID}

# ── Telegram notifications (recommended) ──────────────────────
# Create bot: @BotFather → /newbot
# Your chat ID: @userinfobot → /start
TELEGRAM_BOT_TOKEN={TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID={TELEGRAM_CHAT_ID}
SAGE_ENABLE_TELEGRAM={SAGE_ENABLE_TELEGRAM}

# ── Make.com Webhook ──────────────────────────────────────────
MAKE_WEBHOOK_URL={MAKE_WEBHOOK_URL}

# ── Cloudflare ────────────────────────────────────────────────
# https://dash.cloudflare.com → My Profile → API Tokens → Create Token
CF_API_TOKEN={CF_API_TOKEN}
CF_ACCOUNT_ID={CF_ACCOUNT_ID}
CF_PAGES_PROJECT_NAME={CF_PAGES_PROJECT_NAME}
CLOUDFLARE_API_TOKEN={CF_API_TOKEN}

# ── ngrok (optional — exposes local server externally) ────────
# https://dashboard.ngrok.com/get-started/your-authtoken
NGROK_AUTHTOKEN={NGROK_AUTHTOKEN}
NGROK_STATIC_DOMAIN={NGROK_STATIC_DOMAIN}

# ── Sage runtime flags ────────────────────────────────────────
SAGE_MOCK_MODE=0
SAGE_SAFE_MODE=0
SAGE_POST_DRY_RUN=0
SAGE_ENABLE_SELF_HEALING=1
SAGE_AUTONOMOUS_ENABLED=0
SAGE_ENABLE_SELF_TEST=1
SAGE_ADMIN_TOKEN={SAGE_ADMIN_TOKEN}
SAGE_BASE_URL=http://localhost:{FLASK_PORT}

# ── Security ──────────────────────────────────────────────────
SAGE_SECURITY_LEDGER_ENABLED=1
SAGE_VAULT_KEY={SAGE_VAULT_KEY}
"""


# ── Section: Core AI ──────────────────────────────────────────────────────────
def section_core() -> dict:
    h("STEP 1 — AI Provider (required)")
    tip("Groq is free and fast. Get your key at: https://console.groq.com/ → API Keys → Create API Key")
    groq = ask("GROQ_API_KEY", secret=True)
    if not groq:
        warn("GROQ_API_KEY not set. You can add it to .env later.")

    p("\nPerplexity is used for the research feature (optional).")
    tip("https://www.perplexity.ai/settings/api")
    perplexity = ask("PERPLEXITY_API_KEY (optional)", secret=True)

    return {"GROQ_API_KEY": groq, "PERPLEXITY_API_KEY": perplexity}


# ── Section: Notion ───────────────────────────────────────────────────────────
def section_notion() -> dict:
    h("STEP 2 — Notion (content database)")
    tip("https://www.notion.so/my-integrations → New integration → copy the token")
    tip("Then duplicate the Sage Content Pool template into your workspace.")
    use_notion = ask_yn("Set up Notion now?")
    if not use_notion:
        return {"NOTION_API_KEY": "", "NOTION_CONTENT_POOL_DB_ID": "",
                "NOTION_EVIDENCE_LEDGER_DB_ID": "", "SAGE_ENABLE_NOTION": "0"}

    key  = ask("NOTION_API_KEY (starts with secret_...)", secret=True)
    pool = ask("Content Pool Database ID (32 chars from the DB page URL)")
    tip("Find the ID in the URL: notion.so/[WORKSPACE]/[32-CHAR-ID]?v=...")
    ledger = ask("Evidence Ledger Database ID (optional)")
    return {
        "NOTION_API_KEY": key,
        "NOTION_CONTENT_POOL_DB_ID": pool,
        "NOTION_EVIDENCE_LEDGER_DB_ID": ledger,
        "SAGE_ENABLE_NOTION": "1" if key else "0",
    }


# ── Section: Bluesky ──────────────────────────────────────────────────────────
def section_bluesky() -> dict:
    h("STEP 3 — Bluesky (SNS auto-posting, recommended)")
    tip("Use an App Password — NOT your main login password.")
    tip("Bluesky → Settings → Privacy and Security → App Passwords → Add App Password")
    use = ask_yn("Set up Bluesky now?")
    if not use:
        return {"BLUESKY_HANDLE": "", "BLUESKY_APP_PASSWORD": "", "SAGE_ENABLE_BLUESKY": "0"}

    handle = ask("Bluesky handle (e.g. yourname.bsky.social — no @)")
    pwd    = ask("App Password (format: xxxx-xxxx-xxxx-xxxx)", secret=True)
    return {"BLUESKY_HANDLE": handle, "BLUESKY_APP_PASSWORD": pwd, "SAGE_ENABLE_BLUESKY": "1"}


# ── Section: Twitter ──────────────────────────────────────────────────────────
def section_twitter() -> dict:
    h("STEP 4 — Twitter / X (optional)")
    tip("https://developer.twitter.com/ → Your Project → Keys and Tokens")
    use = ask_yn("Set up Twitter/X?", default=False)
    if not use:
        return {k: "" for k in ["TWITTER_API_KEY", "TWITTER_API_SECRET",
                                  "TWITTER_ACCESS_TOKEN", "TWITTER_ACCESS_TOKEN_SECRET",
                                  "TWITTER_BEARER_TOKEN"]}
    return {
        "TWITTER_API_KEY":              ask("TWITTER_API_KEY", secret=True),
        "TWITTER_API_SECRET":           ask("TWITTER_API_SECRET", secret=True),
        "TWITTER_ACCESS_TOKEN":         ask("TWITTER_ACCESS_TOKEN", secret=True),
        "TWITTER_ACCESS_TOKEN_SECRET":  ask("TWITTER_ACCESS_TOKEN_SECRET", secret=True),
        "TWITTER_BEARER_TOKEN":         ask("TWITTER_BEARER_TOKEN", secret=True),
    }


# ── Section: Instagram ────────────────────────────────────────────────────────
def section_instagram() -> dict:
    h("STEP 5 — Instagram (optional — requires Business account)")
    tip("Needs Facebook Business account + Instagram Graph API access.")
    tip("Recommendation: start with Bluesky only, add Instagram later.")
    use = ask_yn("Set up Instagram?", default=False)
    if not use:
        return {"INSTAGRAM_ACCESS_TOKEN": "", "INSTAGRAM_ACCOUNT_ID": ""}
    return {
        "INSTAGRAM_ACCESS_TOKEN": ask("INSTAGRAM_ACCESS_TOKEN", secret=True),
        "INSTAGRAM_ACCOUNT_ID":   ask("INSTAGRAM_ACCOUNT_ID (numeric ID)"),
    }


# ── Section: Telegram ─────────────────────────────────────────────────────────
def section_telegram() -> dict:
    h("STEP 6 — Telegram notifications (recommended)")
    tip("1. Message @BotFather on Telegram → /newbot → copy the token")
    tip("2. Message @userinfobot → /start → copy your Chat ID")
    use = ask_yn("Set up Telegram notifications?", default=True)
    if not use:
        return {"TELEGRAM_BOT_TOKEN": "", "TELEGRAM_CHAT_ID": "", "SAGE_ENABLE_TELEGRAM": "0"}
    return {
        "TELEGRAM_BOT_TOKEN":   ask("TELEGRAM_BOT_TOKEN", secret=True),
        "TELEGRAM_CHAT_ID":     ask("TELEGRAM_CHAT_ID (numeric ID)"),
        "SAGE_ENABLE_TELEGRAM": "1",
    }


# ── Section: Cloudflare ───────────────────────────────────────────────────────
def section_cloudflare() -> dict:
    h("STEP 7 — Cloudflare (cloud deployment)")
    tip("https://dash.cloudflare.com → My Profile → API Tokens → Create Token")
    tip("Use the 'Edit Cloudflare Workers' template.")
    use = ask_yn("Set up Cloudflare now?")
    if not use:
        return {"CF_API_TOKEN": "", "CF_ACCOUNT_ID": "", "CF_PAGES_PROJECT_NAME": "sage-ai",
                "NGROK_AUTHTOKEN": "", "NGROK_STATIC_DOMAIN": "", "SITE_URL": ""}

    token   = ask("CF_API_TOKEN", secret=True)
    account = ask("CF_ACCOUNT_ID (32-char ID in your dashboard URL)")
    tip("Find it in: dash.cloudflare.com/[ACCOUNT_ID]/...")
    project = ask("Cloudflare Pages project name", default="sage-ai")
    site    = ask(f"Your Pages URL (e.g. https://{project}.pages.dev)", default=f"https://{project}.pages.dev")

    p("\nngrok lets you expose your local server externally (optional).")
    tip("https://dashboard.ngrok.com/get-started/your-authtoken")
    ngrok        = ask("NGROK_AUTHTOKEN (optional)", secret=True)
    ngrok_domain = ask("NGROK static domain (optional, e.g. yourname.ngrok-free.app)")

    return {
        "CF_API_TOKEN":           token,
        "CF_ACCOUNT_ID":          account,
        "CF_PAGES_PROJECT_NAME":  project,
        "SITE_URL":               site,
        "NGROK_AUTHTOKEN":        ngrok,
        "NGROK_STATIC_DOMAIN":    ngrok_domain,
    }


# ── Section: Misc ─────────────────────────────────────────────────────────────
def section_misc() -> dict:
    h("STEP 8 — Other integrations (all optional)")
    make = ask("Make.com Webhook URL (for Stripe → Telegram/Notion alerts)")
    gumroad = ask("GUMROAD_ACCESS_TOKEN", secret=True)
    return {"GUMROAD_ACCESS_TOKEN": gumroad, "MAKE_WEBHOOK_URL": make}


# ── Section: Identity ─────────────────────────────────────────────────────────
def section_identity():
    """Set up the AI content identity (tone, niche, audience)."""
    h("STEP 9 — Your Sage AI Identity")
    p("This controls the tone and niche of all generated content.")
    tip("You can edit backend/config/identity.json any time to change this.")

    role     = ask("Your AI's role/title",          default="AI monetization expert")
    niche    = ask("Your niche (content focus)",     default="AI-powered side income and automation for solopreneurs")
    tone     = ask("Content tone",                   default="professional yet approachable")
    brand    = ask("Brand name",                     default="Sage AI")
    audience = ask("Target audience",                default="English-speaking solopreneurs who want passive income with AI tools")

    identity = {
        "role": role,
        "niche": niche,
        "tone": tone,
        "visual_style": "clean minimalist tech aesthetic",
        "language": "en",
        "brand_name": brand,
        "target_audience": audience,
    }

    identity_path = Path(__file__).parent / "backend" / "config" / "identity.json"
    import json
    with open(identity_path, "w", encoding="utf-8") as f:
        json.dump(identity, f, ensure_ascii=False, indent=2)
    ok(f"Saved identity.json: {identity_path}")
    return identity


# ── Workers setup instructions ────────────────────────────────────────────────
def show_workers_instructions(config: dict):
    h("STEP 10 — Cloudflare Workers setup (manual step)")
    p("""
The Sage automation workers need to be deployed to Cloudflare separately.
Follow these steps after this wizard finishes:
""", YELLOW)

    account_id = config.get("CF_ACCOUNT_ID", "YOUR_CLOUDFLARE_ACCOUNT_ID")
    notion_db  = config.get("NOTION_CONTENT_POOL_DB_ID", "YOUR_NOTION_DATABASE_ID")
    bsky       = config.get("BLUESKY_HANDLE", "yourhandle.bsky.social")

    p(f"""  1. Open  workers/sage-sns-worker/wrangler.toml  and fill in:
       account_id                = "{account_id}"
       BLUESKY_HANDLE            = "{bsky}"
       NOTION_CONTENT_POOL_DB_ID = "{notion_db}"

  2. Open  workers/sage-content-replenisher/wrangler.toml  and fill in:
       account_id                = "{account_id}"
       NOTION_CONTENT_POOL_DB_ID = "{notion_db}"

  3. In your terminal, run:
       cd workers/sage-sns-worker
       wrangler login        (first time only)
       npm install
       npm run deploy
       wrangler secret put GROQ_API_KEY
       wrangler secret put NOTION_API_KEY
       wrangler secret put BLUESKY_APP_PASSWORD

       cd ../sage-content-replenisher
       npm install
       npm run deploy
       wrangler secret put GROQ_API_KEY
       wrangler secret put NOTION_API_KEY

  4. In your Notion Content Pool database:
       - Make sure there is a "Status" select property
       - Use "Scheduled" for pending posts, "Done" for completed posts

  See Sage_AI_Setup_Guide.docx for screenshots and troubleshooting.
""", CYAN)


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    check_python_version()
    banner()

    p("This script will create a new .env file with your configuration.", YELLOW)
    env_path = Path(__file__).parent / ".env"
    if env_path.exists():
        if not ask_yn("\nExisting .env found. Overwrite it?", default=False):
            p("Setup cancelled. Your existing .env was not changed.", RED)
            sys.exit(0)
        shutil.copy(env_path, env_path.with_suffix(".env.backup"))
        ok("Backed up existing config to .env.backup")

    # Collect all config values
    config = {}
    config.update(section_core())
    config.update(section_notion())
    config.update(section_bluesky())
    config.update(section_twitter())
    config.update(section_instagram())
    config.update(section_telegram())
    config.update(section_cloudflare())
    config.update(section_misc())

    # Fixed / auto-generated values
    import secrets
    config["FLASK_PORT"]       = "8080"
    config["SAGE_ADMIN_TOKEN"] = secrets.token_hex(16)
    config["SAGE_VAULT_KEY"]   = secrets.token_hex(32)

    # Ensure all template keys have a value (even if empty)
    defaults = {
        "SITE_URL": "", "PERPLEXITY_API_KEY": "",
        "NOTION_EVIDENCE_LEDGER_DB_ID": "",
        "TWITTER_API_KEY": "", "TWITTER_API_SECRET": "",
        "TWITTER_ACCESS_TOKEN": "", "TWITTER_ACCESS_TOKEN_SECRET": "",
        "TWITTER_BEARER_TOKEN": "",
        "INSTAGRAM_ACCESS_TOKEN": "", "INSTAGRAM_ACCOUNT_ID": "",
        "TELEGRAM_BOT_TOKEN": "", "TELEGRAM_CHAT_ID": "",
        "SAGE_ENABLE_TELEGRAM": "0",
        "MAKE_WEBHOOK_URL": "", "GUMROAD_ACCESS_TOKEN": "",
        "CF_API_TOKEN": "", "CF_ACCOUNT_ID": "",
        "CF_PAGES_PROJECT_NAME": "sage-ai",
        "NGROK_AUTHTOKEN": "", "NGROK_STATIC_DOMAIN": "",
    }
    for k, v in defaults.items():
        config.setdefault(k, v)

    # Identity setup
    section_identity()

    # Write .env
    h("Saving your .env file...")
    env_content = ENV_TEMPLATE.format(**config)
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)
    ok(f"Created: {env_path}")

    # Protect .gitignore
    gitignore_path = Path(__file__).parent / ".gitignore"
    if gitignore_path.exists():
        content = gitignore_path.read_text()
        if ".env" not in content:
            with open(gitignore_path, "a") as f:
                f.write("\n.env\n")
            ok("Added .env to .gitignore")
    else:
        warn("No .gitignore found. Make sure you never commit your .env file!")

    # Install Python packages
    h("STEP 10a — Install Python packages")
    if ask_yn("Install packages from backend/requirements.txt now?"):
        req_path = Path(__file__).parent / "backend" / "requirements.txt"
        if req_path.exists():
            subprocess.run([sys.executable, "-m", "pip", "install", "-r", str(req_path)],
                           check=False)
            ok("Python packages installed")
        else:
            warn(f"requirements.txt not found at: {req_path}")

    # Build frontend
    h("STEP 10b — Build the frontend")
    if ask_yn("Run  npm install && npm run build  now?"):
        proj_dir = Path(__file__).parent
        subprocess.run(["npm", "install"], cwd=proj_dir, check=False)
        subprocess.run(["npm", "run", "build"], cwd=proj_dir, check=False)
        ok("Frontend built successfully")

    # Workers instructions
    show_workers_instructions(config)

    # Done
    h("Setup complete!")
    p(f"""
Next steps:

  1. Follow the Workers deployment instructions shown above (STEP 10).

  2. Start the local dashboard:
       Windows:    .\\run_sage.ps1
       Mac/Linux:  python backend/flask_server.py

  3. Open your browser:
       http://localhost:8080

  4. Full guide with screenshots:
       Open  Sage_AI_Setup_Guide.docx  in your Sage folder.

Support: Set VITE_SUPPORT_EMAIL in your .env for your support contact.
""", GREEN)


if __name__ == "__main__":
    main()
