import requests
import os
import logging
import time
import json

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class DevToIntegration:
    """
    DEV.to Integration Agent.
    Supports posting articles via API.
    Includes Mock Mode for testing without API keys.
    """
    def __init__(self):
        self.api_key = os.environ.get('DEVTO_API_KEY')
        self.base_url = "https://dev.to/api"
        self.mock_mode = False

        if not self.api_key:
            logger.warning("⚠️ DEVTO_API_KEY not found. Running in MOCK MODE.")
            self.mock_mode = True
        else:
            logger.info("✅ DEV.to API Initialized")

    def post_article(self, title, content_markdown, tags=[], cover_image=None, published=False):
        """
        Post an article to DEV.to.
        """
        if self.mock_mode:
            return self._mock_post(title, content_markdown, tags, cover_image, published)

        headers = {
            "api-key": self.api_key,
            "Content-Type": "application/json"
        }

        article_data = {
            "article": {
                "title": title,
                "body_markdown": content_markdown,
                "published": published,
                "tags": tags
            }
        }
        
        if cover_image:
            article_data["article"]["main_image"] = cover_image

        try:
            response = requests.post(f"{self.base_url}/articles", json=article_data, headers=headers, timeout=10)
            response.raise_for_status()
            
            data = response.json()
            logger.info(f"✅ Posted to DEV.to: {data.get('url')}")
            
            return {
                "status": "success",
                "url": data.get('url'),
                "id": data.get('id'),
                "platform": "dev.to"
            }
        except requests.exceptions.RequestException as e:
            logger.error(f"❌ DEV.to Post Failed: {e}")
            return {"status": "error", "message": str(e)}

    def _mock_post(self, title, content, tags, cover_image, published):
        """Simulate a successful post."""
        time.sleep(1.0) # Simulate network latency
        
        slug = title.lower().replace(" ", "-")
        mock_id = int(time.time())
        mock_url = f"https://dev.to/sage-ai/{slug}-{mock_id}"
        
        logger.info(f"🤖 [MOCK] Posted to DEV.to")
        logger.info(f"    Title: {title}")
        logger.info(f"    Tags: {tags}")
        logger.info(f"    Published: {published}")
        
        return {
            "status": "success",
            "url": mock_url,
            "id": mock_id,
            "platform": "dev.to",
            "mode": "mock"
        }

if __name__ == "__main__":
    # Self-test
    agent = DevToIntegration()
    res = agent.post_article(
        title="Hello from Sage AI",
        content_markdown="**This is a test post.**\n\nGenerated by Sage AI.",
        tags=["ai", "python", "automation"],
        published=False
    )
    print(res)
