import requests
import os
import logging
import time

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class HashnodeIntegration:
    """
    Hashnode Integration Agent.
    Supports posting articles via GraphQL API.
    Includes Mock Mode for testing without API keys.
    """
    def __init__(self):
        self.api_key = os.environ.get('HASHNODE_API_KEY')
        self.base_url = "https://gql.hashnode.com"
        self.publication_id = os.environ.get('HASHNODE_PUBLICATION_ID')
        self.mock_mode = False

        if not self.api_key or not self.publication_id:
            logger.warning("⚠️ HASHNODE_API_KEY or HASHNODE_PUBLICATION_ID not found. Running in MOCK MODE.")
            self.mock_mode = True
        else:
            logger.info("✅ Hashnode API Initialized")

    def post_article(self, title, content_markdown, tags=[], cover_image=None):
        """
        Post an article to Hashnode using GraphQL.
        """
        if self.mock_mode:
            return self._mock_post(title, content_markdown, tags, cover_image)

        headers = {
            "Authorization": self.api_key,
            "Content-Type": "application/json"
        }

        mutation = """
        mutation PublishPost($input: PublishPostInput!) {
            publishPost(input: $input) {
                post {
                    id
                    slug
                    url
                }
            }
        }
        """

        variables = {
            "input": {
                "title": title,
                "contentMarkdown": content_markdown,
                "tags": [{"name": tag} for tag in tags],
                "publicationId": self.publication_id
            }
        }

        if cover_image:
            variables["input"]["coverImageOptions"] = {"coverImageURL": cover_image}

        try:
            response = requests.post(
                self.base_url,
                json={"query": mutation, "variables": variables},
                headers=headers,
                timeout=10
            )
            response.raise_for_status()
            
            data = response.json()
            if "errors" in data:
                logger.error(f"❌ Hashnode API Error: {data['errors']}")
                return {"status": "error", "message": str(data['errors'])}
            
            post_url = data["data"]["publishPost"]["post"]["url"]
            logger.info(f"✅ Posted to Hashnode: {post_url}")
            
            return {
                "status": "success",
                "url": post_url,
                "id": data["data"]["publishPost"]["post"]["id"],
                "platform": "hashnode"
            }
        except requests.exceptions.RequestException as e:
            logger.error(f"❌ Hashnode Post Failed: {e}")
            return {"status": "error", "message": str(e)}

    def _mock_post(self, title, content, tags, cover_image):
        """Simulate a successful post."""
        time.sleep(1.0)
        
        slug = title.lower().replace(" ", "-")
        mock_url = f"https://sageai.hashnode.dev/{slug}"
        
        logger.info(f"🤖 [MOCK] Posted to Hashnode")
        logger.info(f"    Title: {title}")
        logger.info(f"    Tags: {tags}")
        
        return {
            "status": "success",
            "url": mock_url,
            "id": "mock_id",
            "platform": "hashnode",
            "mode": "mock"
        }

if __name__ == "__main__":
    # Self-test
    agent = HashnodeIntegration()
    res = agent.post_article(
        title="Hello from Sage AI",
        content_markdown="**This is a test post.**\n\nGenerated by Sage AI.",
        tags=["ai", "python", "automation"]
    )
    print(res)
