import os
import opik

# Configure Opik
opik.configure(use_local=False)

class LocalHTMLIntegration:
    def __init__(self):
        self.name = "Local HTML Generator"
        self.output_dir = os.path.join(os.getcwd(), "generated_sites")
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    @opik.track(name="generate_local_site")
    def create_site(self, title: str, content: str, video_path: str = None) -> dict:
        print(f"🌐 Generating Local HTML Site: {title}")
        
        # Simple template
        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{title}</title>
            <style>
                body {{ font-family: 'Helvetica Neue', sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
                h1 {{ color: #2c3e50; }}
                .video-container {{ margin: 20px 0; }}
                video {{ max-width: 100%; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
                .content {{ background: #f9f9f9; padding: 20px; border-radius: 8px; }}
            </style>
        </head>
        <body>
            <h1>{title}</h1>
            
            <div class="video-container">
                {f'<video controls src="{video_path}"></video>' if video_path else ''}
            </div>
            
            <div class="content">
                {content.replace(chr(10), '<br>')}
            </div>
            
            <footer>
                <p>Generated by Sage 2.0</p>
            </footer>
        </body>
        </html>
        """
        
        # Sanitize filename
        safe_title = "".join([c for c in title if c.isalnum() or c in (' ', '-', '_')]).strip()
        filename = f"{safe_title.lower().replace(' ', '_')}.html"
        file_path = os.path.join(self.output_dir, filename)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html_content)
            
        return {"status": "success", "url": f"file:///{file_path.replace(os.sep, '/')}", "path": file_path}

local_html = LocalHTMLIntegration()
