"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useLang } from "@/lib/i18n";

// セルフサーブ接続ハブ: ユーザーが自分のMeta広告アカウント／TikTokを接続する。
// App Reviewのスクリーンキャスト撮影＆テスター検証にも使う。
export default function ConnectPage() {
  const { lang } = useLang();
  const isEn = lang === "en";
  const [deviceId, setDeviceId] = useState("global");

  useEffect(() => {
    try { setDeviceId(localStorage.getItem("growl_device_id") || "global"); } catch {}
  }, []);

  const metaUrl = `/api/meta-ads/oauth-start?device_id=${encodeURIComponent(deviceId)}`;
  const tiktokUrl = `/api/auth/tiktok?device_id=${encodeURIComponent(deviceId)}`;

  return (
    <main className="min-h-screen bg-gray-50 flex flex-col items-center px-4 py-12">
      <div className="w-full max-w-md">
        <Link href="/dashboard" className="text-sm text-gray-400 hover:text-gray-600">{isEn ? "← Dashboard" : "← ダッシュボード"}</Link>
        <h1 className="text-2xl font-bold text-gray-900 mt-4 mb-2">{isEn ? "Connect your accounts" : "アカウントを接続"}</h1>
        <p className="text-sm text-gray-600 leading-relaxed mb-6">
          {isEn
            ? "Connect your own ad accounts so Growl can create and manage campaigns for you. You can disconnect anytime."
            : "あなた自身の広告アカウントを接続すると、Growlが広告の作成・運用を代行できます。いつでも解除できます。"}
        </p>

        <div className="space-y-3">
          {/* Meta */}
          <div className="bg-white border border-gray-100 rounded-2xl p-5 shadow-sm">
            <div className="flex items-center gap-3 mb-2">
              <span className="text-2xl">📘</span>
              <p className="font-bold text-gray-900">{isEn ? "Facebook / Instagram Ads" : "Facebook / Instagram 広告"}</p>
            </div>
            <p className="text-xs text-gray-500 mb-3">
              {isEn
                ? "Create, run, and optimize Meta ads on your own ad account. Reads performance to improve results."
                : "あなたの広告アカウントでMeta広告を作成・配信・最適化。成果を読み取り改善します。"}
            </p>
            <a href={metaUrl}
              className="block text-center bg-[#1877F2] hover:opacity-90 text-white font-bold py-3 rounded-xl transition-opacity">
              {isEn ? "Connect Facebook →" : "Facebookを接続 →"}
            </a>
          </div>

          {/* TikTok */}
          <div className="bg-white border border-gray-100 rounded-2xl p-5 shadow-sm">
            <div className="flex items-center gap-3 mb-2">
              <span className="text-2xl">🎵</span>
              <p className="font-bold text-gray-900">TikTok</p>
            </div>
            <p className="text-xs text-gray-500 mb-3">
              {isEn
                ? "Connect TikTok to auto-post videos generated by Growl."
                : "TikTokを接続して、Growlが生成した動画を自動投稿します。"}
            </p>
            <a href={tiktokUrl}
              className="block text-center bg-black hover:opacity-90 text-white font-bold py-3 rounded-xl transition-opacity">
              {isEn ? "Connect TikTok →" : "TikTokを接続 →"}
            </a>
          </div>
        </div>

        <p className="mt-6 text-[11px] text-gray-400 leading-relaxed">
          {isEn
            ? "Growl only accesses accounts you explicitly connect. To remove your data and revoke tokens, use the "
            : "Growlはあなたが明示的に接続したアカウントのみにアクセスします。データ削除とトークン無効化は"}
          <Link href="/data-deletion" className="underline">{isEn ? "data deletion page" : "データ削除ページ"}</Link>
          {isEn ? "." : "から。"}
        </p>
      </div>
    </main>
  );
}
