/**
 * CF Pages Function: /api/generate
 * Cloud-native content generation — Groq API (no Flask / no PC required)
 *
 * POST /api/generate
 * Body: { topic: string, market?: string, language?: string }
 *
 * Required CF Pages env var:
 *   GROQ_API_KEY
 */

const GROQ_API = 'https://api.groq.com/openai/v1/chat/completions';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Content-Type': 'application/json',
};

async function callGroq(apiKey, systemPrompt, userPrompt, maxTokens = 2000) {
  const res = await fetch(GROQ_API, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      max_tokens: maxTokens,
      temperature: 0.75,
    }),
  });
  const data = await res.json();
  return data.choices?.[0]?.message?.content?.trim() || '';
}

export async function onRequestPost(context) {
  const { request, env } = context;

  try {
    const body = await request.json();
    const topic = body.topic || 'AI automation for solopreneurs';
    const market = body.market || 'English-speaking solopreneurs';

    const groqKey = env.GROQ_API_KEY;
    if (!groqKey) {
      return new Response(JSON.stringify({
        error: 'GROQ_API_KEY not set',
        qa_status: 'FAIL',
      }), { status: 503, headers: corsHeaders });
    }

    // Generate blog sections + SNS captions in parallel
    const [sectionsRaw, captionsRaw] = await Promise.all([
      callGroq(
        groqKey,
        `You are an expert content writer for solopreneurs. Write clear, practical, well-structured blog content in English.`,
        `Write a 3-section blog post about: "${topic}"
         Target audience: ${market}

         Format as JSON array:
         [
           {"title": "...", "content": "... (200-300 words, practical, specific numbers)"},
           {"title": "...", "content": "..."},
           {"title": "...", "content": "..."}
         ]

         Output JSON only, no explanation.`,
        2000
      ),
      callGroq(
        groqKey,
        `You are an expert social media writer for solopreneurs.`,
        `Write 3 social media captions about: "${topic}"
         Each caption: 200-280 chars, start with emoji, end with 3 hashtags, practical and engaging.

         Format as JSON array of strings.
         Output JSON only.`,
        600
      ),
    ]);

    // Parse sections
    let sections = [];
    try {
      const match = sectionsRaw.match(/\[[\s\S]*\]/);
      if (match) sections = JSON.parse(match[0]);
    } catch (_) {
      sections = [{ title: topic, content: sectionsRaw }];
    }

    // Parse captions
    let captions = [];
    try {
      const match = captionsRaw.match(/\[[\s\S]*\]/);
      if (match) captions = JSON.parse(match[0]);
    } catch (_) {
      captions = [captionsRaw];
    }

    // Generate image URLs via Pollinations (free, no API key)
    const images = {};
    sections.forEach((s, i) => {
      const seed = 100 + i * 101;
      const prompt = encodeURIComponent(`${s.title}, professional digital art, solopreneur AI automation, dark futuristic`);
      images[s.title] = {
        type: 'generated',
        url: `https://image.pollinations.ai/prompt/${prompt}?seed=${seed}&width=400&height=225&nologo=true`,
      };
    });

    return new Response(JSON.stringify({
      qa_status: 'PASS',
      research_source: 'groq_cloud',
      topic,
      sections,
      captions,
      images,
      sales_page: `# ${topic}\n\n${sections.map(s => `## ${s.title}\n\n${s.content}`).join('\n\n')}\n\n---\n*Generated by Sage AI*`,
    }), { headers: corsHeaders });

  } catch (err) {
    return new Response(JSON.stringify({
      error: 'Generation failed', detail: String(err), qa_status: 'FAIL',
    }), { status: 500, headers: corsHeaders });
  }
}

export async function onRequestOptions() {
  return new Response(null, {
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    },
  });
}
