"""
Sage 3.0: Google Disco GenTab Generator (Local Edition)
Powered by Groq Llama 3.3
Refined Version: Templates + File persistence
"""

import os
import json
import logging
import requests
import datetime
import re
from typing import List, Dict, Any
from pathlib import Path

logger = logging.getLogger(__name__)

class GenTabGenerator:
    """
    Generates HTML Apps for specific tasks/contexts.
    Uses Groq API to fill templates and saves them to frontend/public/gentabs/.
    """
    
    def __init__(self, model: str = "llama-3.3-70b-versatile"):
        self.api_key = os.getenv("GROQ_API_KEY")
        self.model = model
        self.api_url = "https://api.groq.com/openai/v1/chat/completions"
        self.frontend_public_path = Path(__file__).parent.parent.parent / "frontend" / "public" / "gentabs"
        self.base_url = "http://localhost:5173/gentabs"
        
        # Ensure directory exists
        self.frontend_public_path.mkdir(parents=True, exist_ok=True)
        
        if not self.api_key:
            logger.warning("⚠️ GROQ_API_KEY not found. GenTab Generator disabled.")

    def _get_template(self, template_type: str = "dashboard") -> str:
        """Returns the base HTML template."""
        # Standard Tailwind template with placeholders
        return """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{TITLE}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: { extend: { colors: { sage: { 500: '#10b981', 600: '#059669', 900: '#064e3b' } } } }
        }
    </script>
    <style>body { background-color: #111827; color: #f3f4f6; }</style>
</head>
<body class="min-h-screen flex flex-col">
    <header class="bg-gray-800 border-b border-gray-700 py-4 px-6 flex justify-between items-center shadow-lg">
        <h1 class="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-sage-500 to-blue-500">
            {PROJECT_NAME}
        </h1>
        <span class="text-xs text-gray-400">Generated by Sage 3.0</span>
    </header>

    <main class="flex-grow container mx-auto p-6 space-y-8">
        <!-- AI Generated Content Injection Point -->
        {CONTENT_BODY}
    </main>

    <footer class="bg-gray-900 border-t border-gray-800 py-4 text-center text-sm text-gray-500">
        Context: {CONTEXT_SUMMARY}
    </footer>
</body>
</html>"""

    def generate_app(self, cluster: Dict[str, Any], all_tabs: List[Dict]) -> str:
        """
        Generate a persistent HTML app for a task cluster.
        Returns the URL to access it.
        """
        if not self.api_key:
            return "http://localhost:5173/error_no_key.html"

        topic = cluster.get('topic', 'My Task')
        summary = cluster.get('summary', '')
        indices = cluster.get('tab_indices', [])
        
        # Filter relevant tabs
        relevant_tabs = []
        for idx in indices:
            if 0 <= idx < len(all_tabs):
                relevant_tabs.append(all_tabs[idx])
                
        # Format tab list for prompt
        tabs_text = "\n".join([f"- {t.get('title')} ({t.get('url')})" for t in relevant_tabs])
        
        # 1. Ask Groq to generate the Body Content (Cards, Lists, etc.)
        prompt = f"""
        You are a UI Engineer. Generate the HTML BODY CONTENT for a task dashboard.
        
        TASK: {topic}
        SUMMARY: {summary}
        
        AVAILABLE TABS (Create links for these):
        {tabs_text}
        
        INSTRUCTIONS:
        1. Output ONLY the HTML structure to go inside the <main> tag.
        2. Use TailwindCSS classes. Dark mode is enabled (bg-gray-900).
        3. Create a "Resource Deck" section with cards for the tabs.
        4. Create a "Action Plan" section with 3-5 checklist items appropriate for this task.
        5. Create a "Quick Notes" textarea.
        6. Do NOT include <html>, <head>, or <body> tags. Just the sections.
        """
        
        try:
            response = requests.post(
                self.api_url,
                headers={"Authorization": f"Bearer {self.api_key}"},
                json={
                    "model": self.model,
                    "messages": [
                        {"role": "system", "content": "You are a code generator. Output only HTML fragments."},
                        {"role": "user", "content": prompt}
                    ],
                    "temperature": 0.5
                },
                timeout=30
            )
            
            if response.status_code != 200:
                logger.error(f"Groq API Error: {response.text}")
                return ""
                
            content_body = response.json()['choices'][0]['message']['content']
            content_body = content_body.replace("```html", "").replace("```", "").strip()
            
            # 2. Fill Template
            template = self._get_template()
            full_html = template.replace("{TITLE}", f"Sage: {topic}") \
                                .replace("{PROJECT_NAME}", topic) \
                                .replace("{CONTENT_BODY}", content_body) \
                                .replace("{CONTEXT_SUMMARY}", summary)
            
            # 3. Save to File
            safe_topic = re.sub(r'[^a-zA-Z0-9]', '_', topic)[:30]
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"app_{timestamp}_{safe_topic}.html"
            file_path = self.frontend_public_path / filename
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(full_html)
                
            logger.info(f"✅ GenTab saved: {file_path}")
            
            # 4. Return URL
            return f"{self.base_url}/{filename}"
            
        except Exception as e:
            logger.error(f"GenTab Generation Failed: {e}")
            return f"Error: {e}"

if __name__ == "__main__":
    # Test logic
    from dotenv import load_dotenv
    env_path = Path(__file__).parent.parent.parent / '.env'
    load_dotenv(env_path)
    
    logging.basicConfig(level=logging.INFO)
    gen = GenTabGenerator()
    
    mock_cluster = {"topic": "Boston Trip", "summary": "Visiting Harvard and MIT"}
    mock_tabs = [{"title": "Harvard Map", "url": "maps.google.com"}, {"title": "MIT Admissions", "url": "mit.edu"}]
    
    url = gen.generate_app(mock_cluster, mock_tabs)
    print(f"Generated URL: {url}")
