import os
import logging
import time
import random
from typing import List
import requests
from PIL import Image, ImageDraw, ImageFont

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class ImageAgent:
    def __init__(self, output_dir="generated_images"):
        self.output_dir = os.path.join(os.getcwd(), output_dir)
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_image(self, prompt):
        """
        Generates an image for the given prompt.
        Currently uses a robust Pillow fallback to ensure valid image files.
        """
        logger.info(f"Generating image for prompt: '{prompt}'")
        
        try:
            # Tier 1: Try Real Stable Diffusion API (Local)
            try:
                from backend.stable_diffusion_api import generate_image_with_sd
                filename = f"img_{int(time.time())}_{random.randint(1000,9999)}"
                path = generate_image_with_sd(prompt, filename)
                logger.info(f"Image generated successfully via SD at: {path}")
                return {"status": "success", "path": path}
            except Exception as sd_error:
                logger.warning(f"Stable Diffusion API failed ({sd_error}). Trying Gemini...")

            # Tier 2: Try LoremFlickr (Stock Photos) - Reliable Fallback
            try:
                # Extract a keyword for the search
                keywords = [w for w in prompt.split() if len(w) > 3]
                keyword = keywords[0] if keywords else "technology"
                
                url = f"https://loremflickr.com/1024/768/{keyword}"
                logger.info(f"Fetching stock photo from: {url}")
                
                resp = requests.get(url, timeout=10)
                if resp.status_code == 200 and len(resp.content) > 1000:
                    filename = f"img_{int(time.time())}_{random.randint(1000,9999)}.jpg"
                    path = os.path.join(self.output_dir, filename)
                    with open(path, 'wb') as f:
                        f.write(resp.content)
                    logger.info(f"Image fetched via LoremFlickr at: {path}")
                    return {"status": "success", "path": path}
                else:
                    logger.warning(f"LoremFlickr returned invalid content (Status: {resp.status_code}, Size: {len(resp.content)})")
            except Exception as cloud_error:
                logger.warning(f"Cloud Image Gen failed ({cloud_error}). Falling back to Pillow.")

            # Tier 3: Robust Fallback (Pillow) - The "Blue Screen"
            # Generate a random pastel color background
            bg_color = (
                random.randint(150, 255),
                random.randint(150, 255),
                random.randint(150, 255)
            )
            
            width, height = 1024, 768
            img = Image.new('RGB', (width, height), bg_color)
            draw = ImageDraw.Draw(img)
            
            # Try to load a nice font, fallback to default
            try:
                font = ImageFont.truetype("arial.ttf", 40)
            except:
                font = ImageFont.load_default()
                
            # Wrap text (simple implementation)
            margin = 50
            offset = 100
            for line in self._wrap_text(prompt, font, width - 2 * margin):
                draw.text((margin, offset), line, font=font, fill=(0, 0, 0))
                offset += 50
                
            # Add watermark
            draw.text((margin, height - 50), "Generated by Sage ImageAgent (Fallback)", font=font, fill=(100, 100, 100))

            # Save
            filename = f"img_{int(time.time())}_{random.randint(1000,9999)}.png"
            path = os.path.join(self.output_dir, filename)
            img.save(path)
            
            logger.info(f"Image generated successfully (Fallback) at: {path}")
            return {"status": "success", "path": path}

        except Exception as e:
            logger.error(f"Image generation failed: {e}", exc_info=True)
            return {"status": "error", "message": str(e)}

    def generate_images_from_script(self, script: str, max_images: int = 5) -> List[str]:
        """
        Generates a batch of images based on a script.
        Splits script by newlines and uses lines as prompts.
        """
        logger.info("Generating batch images from script...")
        prompts = [line.strip() for line in script.split('\n') if len(line.strip()) > 10][:max_images]
        
        paths = []
        for prompt in prompts:
            res = self.generate_image(prompt)
            if res['status'] == 'success':
                paths.append(res['path'])
        
        return paths

    def _wrap_text(self, text, font, max_width):
        """Simple text wrapper"""
        lines = []
        if not text: return lines
        
        # This is a very basic wrapper, for default font it might be inaccurate
        # but sufficient for fallback
        words = text.split()
        current_line = words[0]
        
        for word in words[1:]:
            if font.getlength(current_line + " " + word) < max_width:
                current_line += " " + word
            else:
                lines.append(current_line)
                current_line = word
        lines.append(current_line)
        return lines

if __name__ == "__main__":
    # Self-test
    agent = ImageAgent()
    res = agent.generate_image("A futuristic city with flying cars and neon lights")
    print(res)
